- name: Start containers
  hosts: all
  strategy: free
  become: true
  pre_tasks:
    - name: Verify if app exists
      ansible.builtin.stat:
        path: /home/app
      register: ret
    - name: Block start
      ansible.builtin.fail:
        msg: "App not exists"
      when: ret.stat.exists != true
  roles:
    - docker-start
