- name: Copy app
  ansible.builtin.copy:
    decrypt: true
    src: files/
    dest: /home
    force: no
- name: Generate docker-composer.override.yml
  ansible.builtin.template:
    src: docker-compose.override.yml.j2
    dest: /home/app/docker-compose.override.yml
- name: Install certificates
  shell: mv /tmp/cert.pem /home/app/volumes/nginx && mv /tmp/key.pem /home/app/volumes/nginx